[workspace]
resolver = "2"
members = [
    "proc-macro",
    "rocket-grants",
]

[workspace.package]
edition = "2021"
rust-version = "1.56"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["rocket", "authz", "security", "grants", "permissions"]
categories = ["authentication"]
homepage = "https://github.com/DDtKey/rocket-grants"
repository = "https://github.com/DDtKey/rocket-grants"
authors = ["DDtKey <ddttkey@gmail.com>"]

[workspace.dependencies]
rocket-grants-proc-macro = { path = "proc-macro" }
rocket-grants = { path = "rocket-grants" }
