[workspace]
resolver = "2"
members = [
    "actix-web-grants",
    "proc-macro",
    "rocket-grants",
    "poem-grants",
]

[workspace.package]
edition = "2021"
rust-version = "1.56"
license = "MIT OR Apache-2.0"
categories = ["authentication"]
homepage = "https://github.com/DDtKey/protect-endpoints"
repository = "https://github.com/DDtKey/protect-endpoints"
authors = ["DDtKey <ddttkey@gmail.com>"]

[workspace.dependencies]
actix-web-grants = { path = "actix-web-grants", version = "4.0.0" }
rocket-grants = { path = "rocket-grants", version = "0.1.1" }
poem-grants = { path = "poem-grants", version = "1.0.0" }
protect-endpoints-proc-macro = { path = "proc-macro", version = "0.1.0" }
