[package]
name = "rocket-grants-proc-macro"
version = "0.5.0-rc.2"
description = "A proc-macro way to validate user permissions for `rocket-grants` crate."
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
readme.workspace = true
categories.workspace = true
license.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1"
syn = { version = "1.0", features = ["full", "derive", "extra-traits"] }

[dev-dependencies]
rocket-grants =  { workspace = true }
rocket = { version = "0.5.0", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
