[package]
name = "poem-grants-proc-macro"
version = "1.0.0-beta.2"
authors = ["DDtKey <ddttkey@gmail.com>"]
description = "A proc-macro way to validate user permissions for `poem-grants` crate."
repository = "https://github.com/DDtKey/poem-grants"
homepage = "https://github.com/DDtKey/poem-grants"
keywords = ["poem", "security", "grants", "codegen", "proc_macro"]
categories = ["authentication"]
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1"
syn = { version = "1.0", features = ["full", "derive", "extra-traits"] }

[dev-dependencies]
poem = "1"
poem-grants =  { path = ".." }
