[package]
name = "actix-grants-proc-macro"
version = "1.0.0"
authors = ["DDtKey <ddttkey@gmail.com>"]
description = "A proc-macro way to validate user permissions for `actix-web-grants` crate."
repository = "https://github.com/DDtKey/actix-web-grants"
homepage = "https://github.com/DDtKey/actix-web-grants"
keywords = ["actix", "security", "grants", "codegen", "proc_macro"]
categories = ["authentication"]
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["full", "derive", "extra-traits"] }

[dev-dependencies]
actix-web = { version = "3.0.0", default-features = false}
actix-web-grants =  { path = "../" }
