[package]
name = "rocket-grants-proc-macro"
version = "0.5.0-beta.1"
authors = ["DDtKey <ddttkey@gmail.com>"]
description = "A proc-macro way to validate user permissions for `rocket-grants` crate."
repository = "https://github.com/DDtKey/rocket-grants"
homepage = "https://github.com/DDtKey/rocket-grants"
keywords = ["rocket", "security", "grants", "codegen", "proc_macro"]
categories = ["authentication"]
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1"
syn = { version = "1.0", features = ["full", "derive", "extra-traits"] }

[dev-dependencies]
rocket-grants =  { path = "../" }
